"""
Problem Statement : You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

# Solution 1:
def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        if s == "":
            return t
        
        hashMap = {}
        for i in range(len(s)):
            if s[i] in hashMap:
                hashMap[s[i]] = hashMap[s[i]] + 1
            else:
                hashMap[s[i]] = 1

        for j in range(len(t)):
            if t[j] in hashMap:
                hashMap[t[j]] = hashMap[t[j]] - 1
            else:
                hashMap[t[j]] = 1

        for k, v in hashMap.items():
            if v == 1 or v == -1:
                return k
                
                
